-- Insert official templates for each category
-- Note: This uses the first admin user found. If no admin exists, templates won't be inserted.

DO $$
DECLARE
  admin_user_id uuid;
BEGIN
  -- Get the first admin user
  SELECT user_id INTO admin_user_id
  FROM public.user_roles
  WHERE role = 'admin'
  LIMIT 1;

  -- Only proceed if an admin user exists
  IF admin_user_id IS NOT NULL THEN
    
    -- Marketing Templates
    INSERT INTO public.prompt_templates (user_id, title, description, category, template, output_type, is_public, is_official) VALUES
    (admin_user_id, 'Product Launch Campaign', 'Create a comprehensive marketing campaign for a new product launch', 'Marketing', 'Create a detailed product launch marketing campaign for [PRODUCT NAME]. Include: 1) Pre-launch teaser strategy, 2) Launch day activities, 3) Post-launch follow-up, 4) Target audience messaging, 5) Key performance indicators to track.', 'text', true, true),
    (admin_user_id, 'Brand Voice Guidelines', 'Develop consistent brand voice and tone guidelines', 'Marketing', 'Create brand voice guidelines for [COMPANY NAME] that operates in [INDUSTRY]. Define: 1) Core brand personality traits, 2) Tone variations for different contexts, 3) Do''s and don''ts, 4) Example phrases, 5) Words to use and avoid.', 'text', true, true),
    (admin_user_id, 'Customer Persona Builder', 'Build detailed customer personas for targeted marketing', 'Marketing', 'Create a detailed customer persona for [PRODUCT/SERVICE]. Include: 1) Demographics, 2) Pain points, 3) Goals and motivations, 4) Buying behavior, 5) Preferred channels, 6) Content preferences, 7) Objections to overcome.', 'text', true, true),
    (admin_user_id, 'A/B Test Ideas Generator', 'Generate creative A/B testing ideas for campaigns', 'Marketing', 'Generate 10 A/B testing ideas for [CAMPAIGN TYPE] to improve [METRIC]. For each test provide: 1) Hypothesis, 2) What to test, 3) Expected outcome, 4) Success criteria, 5) Potential risks.', 'text', true, true),
    (admin_user_id, 'Influencer Outreach Template', 'Craft personalized influencer collaboration pitches', 'Marketing', 'Write a personalized influencer outreach message for [INFLUENCER NAME] to promote [PRODUCT/SERVICE]. Include: 1) Personalized opening, 2) Value proposition, 3) Collaboration benefits, 4) Specific campaign details, 5) Clear call-to-action.', 'text', true, true),
    (admin_user_id, 'Marketing Budget Allocator', 'Optimize marketing budget across channels', 'Marketing', 'Create a marketing budget allocation strategy for [COMPANY] with a budget of [AMOUNT]. Distribute across: 1) Digital advertising, 2) Content marketing, 3) Social media, 4) Events, 5) PR, 6) Tools and software. Justify each allocation.', 'text', true, true),
    (admin_user_id, 'Competitor Analysis Framework', 'Analyze competitors and identify opportunities', 'Marketing', 'Perform a comprehensive competitor analysis for [YOUR COMPANY] vs [COMPETITORS]. Include: 1) Product comparison, 2) Pricing strategy, 3) Marketing tactics, 4) Strengths and weaknesses, 5) Market positioning, 6) Differentiation opportunities.', 'text', true, true),
    (admin_user_id, 'Landing Page Copy Formula', 'Write high-converting landing page copy', 'Marketing', 'Write landing page copy for [PRODUCT/SERVICE] targeting [AUDIENCE]. Include: 1) Attention-grabbing headline, 2) Subheadline, 3) Benefits-focused body copy, 4) Social proof section, 5) FAQ, 6) Multiple CTA variations, 7) Urgency elements.', 'text', true, true),
    (admin_user_id, 'Referral Program Strategy', 'Design a viral referral program', 'Marketing', 'Design a referral program for [PRODUCT/SERVICE]. Include: 1) Referral incentives for both parties, 2) Easy sharing mechanics, 3) Viral loop optimization, 4) Fraud prevention, 5) Success metrics, 6) Promotional messaging.', 'text', true, true),
    (admin_user_id, 'Crisis Communication Plan', 'Prepare for reputation management scenarios', 'Marketing', 'Create a crisis communication plan for [SCENARIO] affecting [COMPANY]. Include: 1) Immediate response protocol, 2) Key messages, 3) Stakeholder communication, 4) Media talking points, 5) Social media strategy, 6) Recovery plan.', 'text', true, true);

    -- Content Creation Templates
    INSERT INTO public.prompt_templates (user_id, title, description, category, template, output_type, is_public, is_official) VALUES
    (admin_user_id, 'Long-Form Blog Article', 'Generate comprehensive, SEO-optimized blog posts', 'Content Creation', 'Write a comprehensive 2000-word blog post about [TOPIC] for [TARGET AUDIENCE]. Include: 1) Engaging introduction with hook, 2) Clear H2 and H3 structure, 3) Data and examples, 4) Actionable takeaways, 5) Conclusion with CTA, 6) Meta description.', 'text', true, true),
    (admin_user_id, 'Video Script Creator', 'Write engaging video scripts with timestamps', 'Content Creation', 'Create a [DURATION] minute video script about [TOPIC]. Include: 1) Hook (0-10s), 2) Introduction (10-30s), 3) Main content with timestamps, 4) Visual cues, 5) B-roll suggestions, 6) Call-to-action, 7) Outro. Format with timestamps.', 'text', true, true),
    (admin_user_id, 'Podcast Episode Outline', 'Structure engaging podcast episodes', 'Content Creation', 'Create a detailed podcast episode outline for [TOPIC/GUEST]. Include: 1) Episode title and description, 2) Intro music notes, 3) Opening monologue, 4) Main talking points with timestamps, 5) Guest questions (if applicable), 6) Sponsor read placements, 7) Outro.', 'text', true, true),
    (admin_user_id, 'Infographic Content Planner', 'Plan data-driven infographics', 'Content Creation', 'Plan an infographic about [TOPIC]. Include: 1) Main headline, 2) 5-7 key data points, 3) Visual flow structure, 4) Color scheme suggestions, 5) Icon ideas, 6) Source citations, 7) CTA at bottom.', 'text', true, true),
    (admin_user_id, 'Case Study Writer', 'Document customer success stories', 'Content Creation', 'Write a compelling case study about [CLIENT/PROJECT]. Include: 1) Client background, 2) Challenge/problem, 3) Solution approach, 4) Implementation details, 5) Results with metrics, 6) Client testimonial, 7) Key takeaways.', 'text', true, true),
    (admin_user_id, 'Newsletter Content Calendar', 'Plan monthly newsletter content', 'Content Creation', 'Create a monthly newsletter content calendar for [AUDIENCE]. For each week include: 1) Main theme, 2) Featured content, 3) Industry news to cover, 4) Product updates, 5) User spotlight, 6) CTA, 7) Engagement question.', 'text', true, true),
    (admin_user_id, 'White Paper Outline', 'Structure authoritative white papers', 'Content Creation', 'Create a white paper outline about [TOPIC] for [INDUSTRY]. Include: 1) Executive summary, 2) Problem statement, 3) Market analysis, 4) Solution framework, 5) Implementation guide, 6) ROI analysis, 7) Conclusion and next steps.', 'text', true, true),
    (admin_user_id, 'Interactive Quiz Creator', 'Design engaging quizzes for audience', 'Content Creation', 'Create an interactive quiz about [TOPIC]. Include: 1) Catchy title, 2) 7-10 questions with 4 answer options each, 3) Scoring logic, 4) 3-5 result categories with descriptions, 5) Shareability hooks, 6) Lead capture strategy.', 'text', true, true),
    (admin_user_id, 'Webinar Script Template', 'Structure educational webinars', 'Content Creation', 'Create a [DURATION] minute webinar script on [TOPIC]. Include: 1) Pre-webinar tech check notes, 2) Opening (5 min), 3) Main content sections with slides, 4) Interactive polls (3-4), 5) Q&A section, 6) Pitch/CTA (5 min), 7) Closing.', 'text', true, true),
    (admin_user_id, 'Storytelling Framework', 'Craft compelling brand stories', 'Content Creation', 'Craft a brand story for [COMPANY/PRODUCT] using the hero''s journey framework. Include: 1) Ordinary world, 2) Call to adventure, 3) Challenges faced, 4) Transformation, 5) Return with solution, 6) Emotional resonance, 7) Universal message.', 'text', true, true);

    -- SEO Templates
    INSERT INTO public.prompt_templates (user_id, title, description, category, template, output_type, is_public, is_official) VALUES
    (admin_user_id, 'Keyword Research Strategy', 'Comprehensive keyword research for any niche', 'SEO', 'Perform keyword research for [TOPIC/NICHE]. Provide: 1) 10 high-volume primary keywords, 2) 20 long-tail variations, 3) Question-based keywords, 4) Competitor keyword gaps, 5) Keyword difficulty estimates, 6) Content type recommendations for each.', 'text', true, true),
    (admin_user_id, 'SEO Content Optimizer', 'Optimize existing content for search engines', 'SEO', 'Analyze and optimize this content for [TARGET KEYWORD]: [PASTE CONTENT]. Provide: 1) Keyword density analysis, 2) Title tag recommendation, 3) Meta description, 4) H2/H3 structure improvements, 5) Internal linking suggestions, 6) Content gaps to fill, 7) Featured snippet optimization.', 'text', true, true),
    (admin_user_id, 'Technical SEO Audit Checklist', 'Identify technical SEO issues', 'SEO', 'Create a technical SEO audit checklist for [WEBSITE]. Include: 1) Site speed issues, 2) Mobile responsiveness, 3) XML sitemap status, 4) Robots.txt review, 5) Schema markup opportunities, 6) Broken links, 7) Canonical tags, 8) Core Web Vitals, 9) HTTPS security.', 'text', true, true),
    (admin_user_id, 'Local SEO Optimizer', 'Optimize for local search rankings', 'SEO', 'Create a local SEO strategy for [BUSINESS] in [LOCATION]. Include: 1) Google Business Profile optimization, 2) Local keywords list, 3) Citation building strategy, 4) Local content ideas, 5) Review generation plan, 6) Local link building tactics, 7) NAP consistency check.', 'text', true, true),
    (admin_user_id, 'Featured Snippet Optimizer', 'Win position zero in search results', 'SEO', 'Optimize content to win featured snippets for [QUERY]. Provide: 1) Current featured snippet analysis, 2) Answer format (paragraph/list/table), 3) Optimal answer length, 4) Structured data markup, 5) Question variations to target, 6) Content structure recommendations.', 'text', true, true),
    (admin_user_id, 'Backlink Strategy Builder', 'Develop ethical backlink acquisition plans', 'SEO', 'Create a backlink building strategy for [WEBSITE] in [INDUSTRY]. Include: 1) Target websites list (DA 50+), 2) Outreach email templates, 3) Content collaboration ideas, 4) Guest post topics, 5) Resource page opportunities, 6) Broken link building targets, 7) Competitor backlink gaps.', 'text', true, true),
    (admin_user_id, 'Content Cluster Planner', 'Plan topic clusters for authority', 'SEO', 'Design a content cluster for the pillar topic [MAIN TOPIC]. Include: 1) Pillar page outline, 2) 10-15 cluster content topics, 3) Internal linking structure, 4) Keyword mapping, 5) Content format for each piece, 6) Publishing schedule, 7) Conversion opportunities.', 'text', true, true),
    (admin_user_id, 'E-commerce SEO Guide', 'Optimize product and category pages', 'SEO', 'Create an SEO strategy for [E-COMMERCE STORE] selling [PRODUCTS]. Include: 1) Product page optimization, 2) Category page structure, 3) Faceted navigation SEO, 4) Product schema markup, 5) User-generated content strategy, 6) Duplicate content solutions, 7) Internal search optimization.', 'text', true, true),
    (admin_user_id, 'Voice Search Optimizer', 'Optimize for voice search queries', 'SEO', 'Optimize content for voice search in [NICHE]. Include: 1) Conversational keywords, 2) Question-based content structure, 3) FAQ schema implementation, 4) Local voice search tactics, 5) Featured snippet optimization, 6) Mobile-first considerations, 7) Natural language processing tips.', 'text', true, true),
    (admin_user_id, 'SERP Analysis Report', 'Analyze search engine results pages', 'SEO', 'Analyze the SERP for [TARGET KEYWORD]. Provide: 1) Top 10 ranking pages analysis, 2) Content length patterns, 3) Common H2/H3 topics, 4) Featured snippets present, 5) SERP features (People Also Ask, etc.), 6) Content gaps, 7) Ranking difficulty assessment, 8) Differentiation opportunities.', 'text', true, true);

    -- Code Templates
    INSERT INTO public.prompt_templates (user_id, title, description, category, template, output_type, is_public, is_official) VALUES
    (admin_user_id, 'API Documentation Generator', 'Create comprehensive API documentation', 'Code', 'Generate API documentation for [API NAME]. Include: 1) Overview and authentication, 2) Base URL and versioning, 3) Endpoint descriptions with HTTP methods, 4) Request/response examples (JSON), 5) Error codes and handling, 6) Rate limiting, 7) Code examples in 3 languages, 8) Changelog.', 'code', true, true),
    (admin_user_id, 'Code Review Checklist', 'Systematic code review framework', 'Code', 'Review this code and provide feedback: [PASTE CODE]. Check: 1) Code quality and readability, 2) Performance issues, 3) Security vulnerabilities, 4) Error handling, 5) Test coverage gaps, 6) Documentation needs, 7) Design patterns used, 8) Refactoring suggestions.', 'code', true, true),
    (admin_user_id, 'Database Schema Designer', 'Design normalized database schemas', 'Code', 'Design a database schema for [APPLICATION TYPE]. Include: 1) Entity relationship diagram, 2) Table structures with data types, 3) Primary and foreign keys, 4) Indexes for performance, 5) Constraints and validations, 6) Sample queries, 7) Migration scripts, 8) Normalization notes.', 'code', true, true),
    (admin_user_id, 'Algorithm Optimizer', 'Improve algorithm efficiency', 'Code', 'Optimize this algorithm: [PASTE CODE]. Provide: 1) Current time complexity analysis, 2) Space complexity analysis, 3) Bottleneck identification, 4) Optimized version with explanation, 5) New time/space complexity, 6) Trade-offs made, 7) Test cases to verify correctness.', 'code', true, true),
    (admin_user_id, 'Testing Strategy Builder', 'Comprehensive testing approach', 'Code', 'Create a testing strategy for [PROJECT/FEATURE]. Include: 1) Unit tests needed, 2) Integration test scenarios, 3) E2E test cases, 4) Edge cases to cover, 5) Mock data requirements, 6) Testing framework recommendations, 7) Coverage goals, 8) CI/CD integration.', 'code', true, true),
    (admin_user_id, 'Security Audit Prompt', 'Identify security vulnerabilities', 'Code', 'Perform a security audit on this code: [PASTE CODE]. Check for: 1) SQL injection vulnerabilities, 2) XSS vulnerabilities, 3) Authentication/authorization issues, 4) Data encryption needs, 5) Input validation, 6) Sensitive data exposure, 7) Dependency vulnerabilities, 8) OWASP Top 10 compliance.', 'code', true, true),
    (admin_user_id, 'Microservice Architecture', 'Design scalable microservices', 'Code', 'Design a microservice architecture for [APPLICATION]. Include: 1) Service boundaries and responsibilities, 2) Communication patterns (sync/async), 3) Data management strategy, 4) API gateway design, 5) Service discovery approach, 6) Error handling and resilience, 7) Monitoring and logging, 8) Deployment strategy.', 'code', true, true),
    (admin_user_id, 'CI/CD Pipeline Builder', 'Automate build and deployment', 'Code', 'Create a CI/CD pipeline for [PROJECT]. Include: 1) Source control workflow, 2) Build process steps, 3) Automated testing stages, 4) Code quality checks, 5) Deployment stages (dev/staging/prod), 6) Rollback strategy, 7) Environment variables management, 8) Monitoring and alerts.', 'code', true, true),
    (admin_user_id, 'Code Documentation Writer', 'Generate clear code documentation', 'Code', 'Write documentation for this code: [PASTE CODE]. Include: 1) Function/class overview, 2) Parameter descriptions, 3) Return value documentation, 4) Usage examples, 5) Edge cases and gotchas, 6) Performance considerations, 7) Dependencies, 8) Version history.', 'code', true, true),
    (admin_user_id, 'Refactoring Assistant', 'Improve code maintainability', 'Code', 'Refactor this code: [PASTE CODE]. Apply: 1) DRY principle, 2) SOLID principles, 3) Design pattern improvements, 4) Naming conventions, 5) Code organization, 6) Complexity reduction, 7) Performance optimization, 8) Before/after comparison with explanations.', 'code', true, true);

    -- Email Templates
    INSERT INTO public.prompt_templates (user_id, title, description, category, template, output_type, is_public, is_official) VALUES
    (admin_user_id, 'Welcome Email Series', 'Onboard new subscribers effectively', 'Email', 'Create a 5-email welcome series for [PRODUCT/SERVICE]. For each email include: 1) Subject line variations, 2) Preview text, 3) Email body copy, 4) Clear CTA, 5) Sending schedule (day 0, 2, 5, 10, 15), 6) Success metrics to track.', 'text', true, true),
    (admin_user_id, 'Cart Abandonment Sequence', 'Recover lost sales via email', 'Email', 'Write a 3-email cart abandonment sequence for [E-COMMERCE STORE]. Include: 1) Email 1 (1 hour later) - reminder, 2) Email 2 (24 hours) - social proof + urgency, 3) Email 3 (72 hours) - discount offer, 4) Subject lines, 5) Personalization tokens, 6) Mobile optimization notes.', 'text', true, true),
    (admin_user_id, 'Newsletter Template', 'Engaging regular newsletters', 'Email', 'Create a newsletter template for [COMPANY/TOPIC]. Include: 1) Catchy subject line, 2) Personal greeting, 3) Main content section, 4) Featured article/product, 5) Quick links/resources, 6) Social media CTA, 7) Unsubscribe footer, 8) Design layout suggestions.', 'text', true, true),
    (admin_user_id, 'Cold Outreach Email', 'Get responses from cold prospects', 'Email', 'Write a cold outreach email to [TARGET PERSONA] for [PRODUCT/SERVICE]. Include: 1) Personalized opening line, 2) Relevant pain point, 3) Value proposition in 2 sentences, 4) Social proof, 5) Soft ask/CTA, 6) PS with alternative offer, 7) Follow-up sequence (3 emails).', 'text', true, true),
    (admin_user_id, 'Re-engagement Campaign', 'Win back inactive subscribers', 'Email', 'Create a re-engagement campaign for inactive subscribers (90+ days). Include: 1) "We miss you" subject line options, 2) Personalized content based on past behavior, 3) Special offer/incentive, 4) Preference center option, 5) Easy unsubscribe, 6) Segmentation criteria, 7) Win-back metrics.', 'text', true, true),
    (admin_user_id, 'Product Launch Email', 'Announce new products with impact', 'Email', 'Write a product launch email for [PRODUCT]. Include: 1) Teaser subject line, 2) Problem-solution opening, 3) Product benefits (3-5 bullets), 4) Visual descriptions, 5) Pricing and offer, 6) Urgency element, 7) Multiple CTAs, 8) FAQ section, 9) Social sharing buttons.', 'text', true, true),
    (admin_user_id, 'Event Invitation Email', 'Drive event registrations', 'Email', 'Create an event invitation email for [EVENT NAME]. Include: 1) Compelling subject line, 2) Event details (date, time, location), 3) Agenda highlights, 4) Speaker/guest information, 5) Benefits of attending, 6) Early bird offer, 7) Registration CTA, 8) Calendar invite attachment, 9) Social proof.', 'text', true, true),
    (admin_user_id, 'Survey Request Email', 'Maximize survey completion rates', 'Email', 'Write a survey request email for [PURPOSE]. Include: 1) Personal subject line, 2) Why their feedback matters, 3) Time estimate (be honest), 4) Incentive if applicable, 5) Anonymous assurance, 6) Direct survey link, 7) Deadline, 8) Thank you note, 9) Follow-up reminder template.', 'text', true, true),
    (admin_user_id, 'Upsell Email Campaign', 'Increase customer lifetime value', 'Email', 'Create an upsell email for existing customers of [PRODUCT A] to upgrade to [PRODUCT B]. Include: 1) Appreciation for current usage, 2) New features/benefits, 3) Usage-based recommendations, 4) Before/after comparison, 5) Limited-time upgrade discount, 6) Easy upgrade process, 7) Money-back guarantee.', 'text', true, true),
    (admin_user_id, 'Apology Email Template', 'Handle customer issues gracefully', 'Email', 'Write an apology email for [ISSUE/MISTAKE]. Include: 1) Sincere apology without excuses, 2) Acknowledgment of impact, 3) Explanation of what happened, 4) Steps taken to fix it, 5) Compensation/gesture of goodwill, 6) Prevention measures, 7) Direct contact for questions, 8) Commitment to improvement.', 'text', true, true);

    -- Social Media Templates
    INSERT INTO public.prompt_templates (user_id, title, description, category, template, output_type, is_public, is_official) VALUES
    (admin_user_id, 'Social Media Content Calendar', 'Plan monthly social media posts', 'Social Media', 'Create a 30-day social media content calendar for [BRAND] on [PLATFORMS]. For each day include: 1) Post copy, 2) Hashtag set (3-5), 3) Image/video description, 4) Best posting time, 5) Engagement prompt, 6) Content pillar category, 7) Link if applicable.', 'text', true, true),
    (admin_user_id, 'Viral Tweet Formula', 'Craft tweets with viral potential', 'Social Media', 'Write 10 tweets about [TOPIC] optimized for engagement. Use formulas: 1) Contrarian take, 2) Thread starter, 3) Question + poll, 4) Relatable humor, 5) Data-driven insight, 6) Story with lesson, 7) Hot take, 8) Resource list, 9) Quote with context, 10) Call for opinions. Include hashtags.', 'text', true, true),
    (admin_user_id, 'Instagram Caption Writer', 'Engaging Instagram captions', 'Social Media', 'Write an Instagram caption for [CONTENT DESCRIPTION]. Include: 1) Hook in first line, 2) Value-driven body (150-200 chars), 3) Story or emotion, 4) Clear CTA, 5) Relevant hashtags (15-20 mixed sizes), 6) Tag suggestions, 7) Engagement question, 8) Alternative shorter version.', 'text', true, true),
    (admin_user_id, 'LinkedIn Thought Leadership', 'Establish authority on LinkedIn', 'Social Media', 'Write a LinkedIn thought leadership post about [INDUSTRY TOPIC]. Include: 1) Attention-grabbing first line, 2) Personal story or experience, 3) Industry insight or trend, 4) Actionable takeaways (3-5), 5) Discussion question, 6) Relevant hashtags (3-5), 7) Professional tone, 8) Optimal length 1300-1500 chars.', 'text', true, true),
    (admin_user_id, 'TikTok Video Script', 'Script short-form videos', 'Social Media', 'Create a TikTok video script about [TOPIC]. Include: 1) Hook in first 3 seconds, 2) Transition descriptions, 3) On-screen text overlays, 4) Voiceover script, 5) Music/sound suggestions, 6) Trending audio to use, 7) Hashtag strategy, 8) Duet/stitch potential, 9) CTA in bio.', 'text', true, true),
    (admin_user_id, 'Facebook Ad Copy', 'Convert with Facebook ads', 'Social Media', 'Write Facebook ad copy for [PRODUCT/SERVICE]. Include: 1) 3 headline variations, 2) Primary text (125 chars), 3) Description text, 4) Pain point addressed, 5) Unique value proposition, 6) Social proof element, 7) Strong CTA, 8) Emoji usage, 9) A/B test variables, 10) Target audience notes.', 'text', true, true),
    (admin_user_id, 'Community Management Responses', 'Handle comments professionally', 'Social Media', 'Create response templates for [BRAND] social media. Include responses for: 1) Positive comments, 2) Questions about products, 3) Complaints, 4) Spam/trolls, 5) Feature requests, 6) Shipping inquiries, 7) Competitors mentioned, 8) Crisis situations, 9) Partnership inquiries, 10) General engagement.', 'text', true, true),
    (admin_user_id, 'Hashtag Research Strategy', 'Find optimal hashtags', 'Social Media', 'Research hashtags for [NICHE/TOPIC] on [PLATFORM]. Provide: 1) 5 high-volume hashtags, 2) 10 medium-volume hashtags, 3) 10 niche-specific hashtags, 4) 5 branded hashtags to create, 5) Competitor hashtag analysis, 6) Trending seasonal hashtags, 7) Hashtag set combinations for different post types.', 'text', true, true),
    (admin_user_id, 'Social Media Crisis Response', 'Handle PR crises on social', 'Social Media', 'Create a social media crisis response plan for [SCENARIO]. Include: 1) Immediate holding statement, 2) Detailed response post, 3) Reply template for comments, 4) Private message template, 5) Escalation criteria, 6) Tone and voice guidelines, 7) Do''s and don''ts, 8) Recovery content plan.', 'text', true, true),
    (admin_user_id, 'User-Generated Content Campaign', 'Drive UGC creation', 'Social Media', 'Design a user-generated content campaign for [BRAND/PRODUCT]. Include: 1) Campaign hashtag, 2) Participation instructions, 3) Content prompt ideas (5-7), 4) Prizes/incentives, 5) Submission guidelines, 6) Rights/permissions language, 7) Showcase plan, 8) Engagement strategy, 9) Success metrics.', 'text', true, true);

  END IF;
END $$;